### ISSUE TITLE
Sporadic session destroy error

### ISSUE THREAD

**Issue by arpost** [eurekaclinical/eurekaclinical-user-webapp#13]
```
1) Error in custom provider, com.google.inject.OutOfScopeException: Cannot access scoped object. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
  at org.eurekaclinical.user.webapp.config.AppModule.configure(AppModule.java:68)
  while locating org.eurekaclinical.user.client.EurekaClinicalUserProxyClient

1 error
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:987)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1013)
	at org.eurekaclinical.user.webapp.config.ClientSessionListener.sessionDestroyed(ClientSessionListener.java:52)
	at org.apache.catalina.session.StandardSession.expire(StandardSession.java:808)
	at org.apache.catalina.session.StandardSession.isValid(StandardSession.java:658)
	at org.apache.catalina.session.ManagerBase.processExpires(ManagerBase.java:534)
	at org.apache.catalina.session.ManagerBase.backgroundProcess(ManagerBase.java:519)
	at org.apache.catalina.core.ContainerBase.backgroundProcess(ContainerBase.java:1352)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1530)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.processChildren(ContainerBase.java:1540)
	at org.apache.catalina.core.ContainerBase$ContainerBackgroundProcessor.run(ContainerBase.java:1519)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.inject.OutOfScopeException: Cannot access scoped object. Either we are not currently inside an HTTP Servlet request, or you may have forgotten to apply com.google.inject.servlet.GuiceFilter as a servlet filter for this request.
	at com.google.inject.servlet.GuiceFilter.getContext(GuiceFilter.java:135)
	at com.google.inject.servlet.GuiceFilter.getRequest(GuiceFilter.java:121)
	at com.google.inject.servlet.ServletScopes$2$1.get(ServletScopes.java:114)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
	at com.google.inject.internal.InjectorImpl$4$1.call(InjectorImpl.java:978)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
	at com.google.inject.internal.InjectorImpl$4.get(InjectorImpl.java:974)
	... 12 more
```

**Comment by arpost** [comment]
I believe this issue has been fixed in eurekaclinical-common (issue https://github.com/eurekaclinical/eurekaclinical-common/issues/7).
